version: '3.8'

services:
  # Production API server
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY:-}
      - HUGGINGFACE_API_TOKEN=${HUGGINGFACE_API_TOKEN:-}
    volumes:
      - ./hyperhelix.log:/app/hyperhelix.log
      - ./errors.log:/app/errors.log

  # Development environment
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY:-}
      - HUGGINGFACE_API_TOKEN=${HUGGINGFACE_API_TOKEN:-}
    volumes:
      # Mount source code for live editing
      - .:/app
      # Preserve Python cache
      - /app/__pycache__
    stdin_open: true
    tty: true
    command: /bin/bash
